version: "3.1"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: Dev-db-Password
      ACCEPT_EULA: "Y"
    volumes:
      - ./.dev/mssql/data:/var/opt/mssql/data
    ports:
      - 5201:1433

  keycloak:
    image: quay.io/keycloak/keycloak:15.1.1
    depends_on:
      - db
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mssql
      DB_ADDR: db
      DB_DATABASE: HaSpMan
      DB_USER: sa
      DB_PASSWORD: Dev-db-Password
      TZ: Europe/Brussels
      KEYCLOAK_IMPORT: /tmp/DevRealm.json
    ports:
      - 5202:8080
    volumes:
      - ./Infrastructure/Keycloak/DevRealm.json:/tmp/DevRealm.json
 
  azurerite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - ./.dev/azurite:/data