apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haspman.fullname" . }}
  labels:
    {{- include "haspman.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_SECRET: {{ required "A valid .Values.haspman.oauth.clientSecret entry required!" .Values.haspman.oauth.clientSecret | b64enc | quote }}
  DB_CONNECTION_STRING: {{ required "A valid .Values.haspman.dbConnectionString entry required!" .Values.haspman.dbConnectionString | b64enc | quote }}