apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haspman.fullname" . }}
  labels:
    {{- include "haspman.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_SECRET: {{ required "A valid .Values.haspman.oauth.clientSecret entry required!" .Values.haspman.oauth.clientSecret | b64enc | quote }}
  DB_CONNECTION_STRING: {{ required "A valid .Values.haspman.dbConnectionString entry required!" .Values.haspman.dbConnectionString | b64enc | quote }}
  STORAGE_CONNECTION_STRING: {{ required "A valid .Values.haspman.storageConnectionString entry required!" .Values.haspman.storageConnectionString | b64enc | quote }}
  {{- if or (.Values.haspman.mailing.mailServer.username) (.Values.haspman.mailing.mailServer.password) }}
  MAILSERVER_USERNAME: {{ required "A valid .Values.haspman.mailing.mailServer.username entry is required" .Values.haspman.mailing.mailServer.username | b64enc | quote  }}
  MAILSERVER_PASSWORD: {{ required "A valid .Values.haspman.mailing.mailServer.password entry is required" .Values.haspman.mailing.mailServer.password | b64enc | quote  }}
  {{- end}}