on:
  workflow_run:
    workflows: [publish]
    branches: [master,helm-chart]
    types: 
      - completed

# Environment variables available to all jobs and steps in this workflow
env:
  CLUSTER_NAME: brixel-common
  CLUSTER_RESOURCE_GROUP: rg-BrixelCommon-univ-weu
  NAMESPACE: haspman-${{env.deplo}}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
        # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - name: Base64 decode helm release values
        id: write_values_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'values.yaml'
          encodedString: ${{ secrets.HASPMAN_VALUES }}
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'dev'
          namespace: 'default'
          chart: 'haspman'
          value-files: ${{ steps.write_values_file.outputs.filePath }} 
          repository: https://brixel.github.io/HaSpMan
        