name: .NET

on:
  push:
    branches: [master, add-docker-build]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test
        run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: .NET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx

  publish:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/brixel/haspman-main
          tags: type=semver,pattern={{version}},value=${{ steps.gitversion.outputs.semVer }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: HaSpMan.Web.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
