name: Publish
on:
  push:
    branches: [master,helm-chart]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/brixel/haspman-main
          tags: type=semver,pattern={{version}},value=${{ steps.gitversion.outputs.semVer }}
      - name: Replace placeholder tokens\
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["Infrastructure/helm-charts/haspman/Chart.yaml"]'
        env:
          GITVERSION_SEMVER: ${{ steps.gitversion.outputs.semVer }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: HaSpMan.Web.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Configure Git
        run: |
          git config user.name "Helm chart releaser"
          git config user.email "helm-chart-releaser@users.noreply.github.com"
      - name: Publish helm chart
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: Infrastructure/helm-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
        # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - name: Base64 decode helm release values
        id: write_values_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'values.yaml'
          encodedString: ${{ secrets.HASPMAN_VALUES }}
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'dev'
          namespace: 'haspman-dev'
          chart: 'haspman'
          value-files: ${{ steps.write_values_file.outputs.filePath }} 
          repository: https://brixel.github.io/HaSpMan