name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-dept: 0
     - name: Docker build
       id: docker_build
       uses: docker/build-push-action@v5
       with:
         context: .
         file: HaSpMan.Web.Dockerfile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: .NET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx